version: "3.5"
services:

  MongoDB:
    image: mongo:4.2
    container_name: "mongodb"
    volumes:
      - /home/mongo/data/db:/data/db
    ports:
      - "27017:27017" 
    restart: on-failure

  node-app:
        image: ibm/nodeapp:latest
        container_name: "nodeapp"
        build: .
        volumes:
            - ./:/usr/src/app
            - /usr/src/app/node_modules/bcrypt/
        ports:
          - "3000:3000" 
        depends_on:
          - "MongoDB" 
         